services:
  web:
    build: ./web
    image: ctf-web:latest
    ports:
      - "${PORT:-80}:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./web/src:/var/www/html
    environment:
      FLAG_LOGIN: "CTF{Initial_Access}"
      FLAG_FILE_UPLOAD: "CTF{File_Upload_RCE}"
      FLAG_ADMIN_ACCESS: "CTF{Admin_Access}"
      FLAG_INSPECTED: "CTF{inspected!}"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bankingai
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      FLAG_CREDENTIAL_HARVESTER: "CTF{Credential_Harvester}"
    volumes:
      - ./db/bankingai.sql:/docker-entrypoint-initdb.d/01_bankingai.sql
      - ./db/init_flags.sh:/docker-entrypoint-initdb.d/02_init_flags.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
